"""empty message

Revision ID: 5adb2d84dfc8
Revises: a422cee852bc
Create Date: 2025-05-15 20:24:03.197240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5adb2d84dfc8'
down_revision = 'a422cee852bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('api_key', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('remark', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_api_key_id')
    )
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.create_index('api_key_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('api_key_api_key_idx', ['api_key'], unique=False)

    op.create_table('end_user',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_end_user_id')
    )
    with op.batch_alter_table('end_user', schema=None) as batch_op:
        batch_op.create_index('end_user_app_id_idx', ['app_id'], unique=False)
        batch_op.create_index('end_user_tenant_id_idx', ['tenant_id'], unique=False)

    op.create_table('wechat_config',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('wechat_app_id', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=True),
    sa.Column('wechat_app_secret', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=True),
    sa.Column('wechat_token', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=True),
    sa.Column('status', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_wechat_config_id')
    )
    with op.batch_alter_table('wechat_config', schema=None) as batch_op:
        batch_op.create_index('wechat_config_app_id_idx', ['app_id'], unique=False)

    op.create_table('wechat_end_user',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('openid', sa.String(), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=False),
    sa.Column('end_user_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_wechat_end_user_id')
    )
    with op.batch_alter_table('wechat_end_user', schema=None) as batch_op:
        batch_op.create_index('wechat_end_user_openid_app_id_idx', ['openid', 'app_id'], unique=False)

    op.create_table('wechat_message',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('wechat_end_user_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('is_pushed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_wechat_message_id')
    )
    with op.batch_alter_table('wechat_message', schema=None) as batch_op:
        batch_op.create_index('wechat_message_wechat_end_user_id_idx', ['wechat_end_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wechat_message', schema=None) as batch_op:
        batch_op.drop_index('wechat_message_wechat_end_user_id_idx')

    op.drop_table('wechat_message')
    with op.batch_alter_table('wechat_end_user', schema=None) as batch_op:
        batch_op.drop_index('wechat_end_user_openid_app_id_idx')

    op.drop_table('wechat_end_user')
    with op.batch_alter_table('wechat_config', schema=None) as batch_op:
        batch_op.drop_index('wechat_config_app_id_idx')

    op.drop_table('wechat_config')
    with op.batch_alter_table('end_user', schema=None) as batch_op:
        batch_op.drop_index('end_user_tenant_id_idx')
        batch_op.drop_index('end_user_app_id_idx')

    op.drop_table('end_user')
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_index('api_key_api_key_idx')
        batch_op.drop_index('api_key_account_id_idx')

    op.drop_table('api_key')
    # ### end Alembic commands ###
