"""empty message

Revision ID: 7f997511fd44
Revises: 0125c1ec79f1
Create Date: 2025-05-28 12:05:13.375431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f997511fd44'
down_revision = '0125c1ec79f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcp_tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool_list', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcp_tool', schema=None) as batch_op:
        batch_op.drop_column('tool_list')

    # ### end Alembic commands ###
