"""empty message

Revision ID: 826531831354
Revises: 5053763c94fe
Create Date: 2024-10-25 09:24:28.444755

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '826531831354'
down_revision = '5053763c94fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('name', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('email', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('avatar', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('password', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=True),
                    sa.Column('password_salt', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=True),
                    sa.Column('last_login_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('last_login_ip', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_account_id')
                    )
    op.create_table('account_oauth',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('account_id', sa.UUID(), nullable=False),
                    sa.Column('provider', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('openid', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('encrypted_token', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_account_oauth_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_oauth')
    op.drop_table('account')
    # ### end Alembic commands ###
