"""empty message

Revision ID: a422cee852bc
Revises: eb4cee7ef581
Create Date: 2025-05-12 16:21:12.729014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a422cee852bc'
down_revision = 'eb4cee7ef581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('tool_call_name', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('icon', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''::text"), nullable=False),
    sa.Column('graph', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('draft_graph', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_debug_passed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_workflow_id')
    )
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.create_index('workflow_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('workflow_tool_call_name_idx', ['tool_call_name'], unique=False)

    op.create_table('workflow_result',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('app_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('graph', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('latency', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('status', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_workflow_result_id')
    )
    with op.batch_alter_table('workflow_result', schema=None) as batch_op:
        batch_op.create_index('workflow_result_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('workflow_result_app_id_idx', ['app_id'], unique=False)
        batch_op.create_index('workflow_result_workflow_id_idx', ['workflow_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_result', schema=None) as batch_op:
        batch_op.drop_index('workflow_result_workflow_id_idx')
        batch_op.drop_index('workflow_result_app_id_idx')
        batch_op.drop_index('workflow_result_account_id_idx')

    op.drop_table('workflow_result')
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.drop_index('workflow_tool_call_name_idx')
        batch_op.drop_index('workflow_account_id_idx')

    op.drop_table('workflow')
    # ### end Alembic commands ###
