"""empty message

Revision ID: e9355133b2f5
Revises: cadf5e2fe816
Create Date: 2024-08-07 15:40:32.418085

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e9355133b2f5'
down_revision = 'cadf5e2fe816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_file',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('account_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('key', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('size', sa.Integer(), server_default=sa.text('0'), nullable=False),
                    sa.Column('extension', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('mime_type', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('hash', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_upload_file_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_file')
    # ### end Alembic commands ###
