"""empty message

Revision ID: ec6935655d25
Revises: 7f997511fd44
Create Date: 2025-05-28 14:05:40.581508

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec6935655d25'
down_revision = '7f997511fd44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcp_tool', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('args_schema', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"),
                      nullable=True))
        batch_op.add_column(
            sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"),
                      nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcp_tool', schema=None) as batch_op:
        batch_op.drop_column('parameters')
        batch_op.drop_column('args_schema')

    # ### end Alembic commands ###
